title: 'Google Summer of Code Blog'
tagline: 'CERN SFT'
email: 'battila93@gmail.com'
description: > # this means to ignore newlines until "baseurl:"
  This is my Blog for Google Summer of Code. I'm working on TMVA (machine learning framework, part of ROOT)
  and Jupyter integration layer at CERN SFT.
baseurl: "" # the subpath of your site, e.g. /blog/
url: ""#"http://qati.github.io" # the base hostname & protocol for your site
logourl: /assets/images/logo.png # Site logo
author: "Attila Bagoly"
author_thumbnail: "/assets/images/avatar.jpg" # Author avatar
# Theme customization - please change from the defaults!
theme:
  # Color for sidebar bar, links, etc
  highlight_color: "#205081" #205081" # "#272935"
  # Social media links, leave blank to ignore
  social:
    github: qati
    twitter: q_ati
    facebook: battila93
    #gplus: battila93
    # dribble: gayanvirajith
    #pinterest: gayanvirajith

  # Enable share buttons on post footer
  show_share_buttons: true

  # Show author picure, name and social links on post footer
  show_author_info: true

  # Disqus comments manager - shortname
  # disqus_shortname: gaya-webcreate

  # Google Analytics/Webmaster key, leave blank to ignore
  google_analytics_key:
  google_webmaster_key:

# Build settings
markdown: kramdown

# Permalinks
permalink: "/:categories/:year/:month/:day/:title/"

gems: [jekyll-paginate]
# Pagination config
paginate: 5


# Files/Folders to be excluded from generated _site folder
exclude:
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

jekyll: bundle exec jekyll serve --watch

# Sass conversion configs
sass:
  sass_dir: assets/css/_sass
  style: :compressed
